# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pycalc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 220, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(10, 260, 181, 23))
        self.pushButton_0.setObjectName("pushButton_0")
        self.equation = QtWidgets.QLabel(self.centralwidget)
        self.equation.setGeometry(QtCore.QRect(20, 20, 371, 61))
        self.equation.setObjectName("equation")
        self.pushButton_addition = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addition.setGeometry(QtCore.QRect(320, 220, 75, 23))
        self.pushButton_addition.setObjectName("pushButton_addition")
        self.pushButton_subtraction = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_subtraction.setGeometry(QtCore.QRect(320, 180, 75, 23))
        self.pushButton_subtraction.setObjectName("pushButton_subtraction")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 140, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(110, 100, 75, 23))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 220, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 180, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 140, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_pos_neg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pos_neg.setGeometry(QtCore.QRect(220, 100, 75, 23))
        self.pushButton_pos_neg.setObjectName("pushButton_pos_neg")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(320, 100, 75, 23))
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(320, 140, 75, 23))
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(320, 260, 75, 23))
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.pushButton_dot.setObjectName("pushButton_dot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_1.setShortcut(_translate("MainWindow", "1"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_0.setShortcut(_translate("MainWindow", "0"))
        self.equation.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_addition.setText(_translate("MainWindow", "+"))
        self.pushButton_addition.setShortcut(_translate("MainWindow", "+"))
        self.pushButton_subtraction.setText(_translate("MainWindow", "-"))
        self.pushButton_subtraction.setShortcut(_translate("MainWindow", "-"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_9.setShortcut(_translate("MainWindow", "9"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_delete.setShortcut(_translate("MainWindow", "Backspace"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_4.setShortcut(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "5"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_clear.setShortcut(_translate("MainWindow", "Del"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_8.setShortcut(_translate("MainWindow", "8"))
        self.pushButton_pos_neg.setText(_translate("MainWindow", "+/-"))
        self.pushButton_pos_neg.setShortcut(_translate("MainWindow", "S"))
        self.pushButton_divide.setText(_translate("MainWindow", "/"))
        self.pushButton_divide.setShortcut(_translate("MainWindow", "/"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_7.setShortcut(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "6"))
        self.pushButton_multiply.setText(_translate("MainWindow", "*"))
        self.pushButton_multiply.setShortcut(_translate("MainWindow", "*"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_equal.setShortcut(_translate("MainWindow", "Enter"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_dot.setShortcut(_translate("MainWindow", "."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

